<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "car_rental"
 *
 * Auto generated by Extension Builder 2017-11-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Car Rental',
    'description' => 'Car Rental TYPO3 example',
    'category' => 'plugin',
    'author' => 'Oliver Hader',
    'author_email' => 'oliver.hader@typo3.org',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
